project:
  type: website
  output-dir: doc
website:
  title: "3960 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd
      - href: Wk6_Intro-to-Exploratory-Data-Analysis.qmd
        text: Into to Exploratory Data Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


